#!/usr/bin/env python3
"""
patch_journeys_admin_ui_v2.py
-------------------------------
Part 3b — follow-up fixes to the Manage Footprints admin form
(run AFTER patch_journeys_admin_ui.py / Part 3).

Changes:
  1. Removes the "Gallery Link" manual text field. Gallery linkage is
     auto-generated by the site builder from category+city/state tags on
     uploaded photos (see _buildJourneysMap's gid pattern) — there's no
     safe manual value to type here, so it's dropped rather than guessed.
  2. Adds auto-geocoding: when you tab out of the State/Country field
     (having typed a Place Name), it automatically looks up latitude and
     longitude via OpenStreetMap's free Nominatim geocoder and fills
     jform-lat / jform-lng. A "Re-check Coordinates" button lets you
     redo the lookup, and you can always edit the fields by hand.

A timestamped backup is written before any edit. If the expected code
isn't found exactly (e.g. Part 3 wasn't run first, or the file has
changed since), the script stops without changing anything.

Run once, locally, AFTER patch_journeys_admin_ui.py:
    python3 patch_journeys_admin_ui_v2.py
"""

import os
import shutil
import datetime

SCRIPT_PATH = "/Users/ncm/Pictures/Mohangraphy/Scripts/Claude_mohangraphy.py"


# ── HTML: replace the form fields block ────────────────────────────────
OLD_FIELDS = (
    "        '      <div class=\"admin-field\"><label>Place Name</label><input id=\"jform-name\" type=\"text\" placeholder=\"e.g. Hampi\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label id=\"jform-region-label\">State</label><input id=\"jform-region\" type=\"text\" placeholder=\"e.g. Karnataka\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label>Latitude</label><input id=\"jform-lat\" type=\"text\" placeholder=\"e.g. 15.3350\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label>Longitude</label><input id=\"jform-lng\" type=\"text\" placeholder=\"e.g. 76.4600\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label>Gallery Link (optional)</label><input id=\"jform-gallery\" type=\"text\" placeholder=\"optional\"></div>\\n'\n"
)
NEW_FIELDS = (
    "        '      <div class=\"admin-field\"><label>Place Name</label><input id=\"jform-name\" type=\"text\" placeholder=\"e.g. Hampi\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label id=\"jform-region-label\">State</label><input id=\"jform-region\" type=\"text\" placeholder=\"e.g. Karnataka\" onblur=\"jformAutoGeocode()\"></div>\\n'\n"
    "        '      <div id=\"jform-geocode-status\" style=\"font-size:9px;color:rgba(255,255,255,0.4);letter-spacing:1px;margin-bottom:8px\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label>Latitude</label><input id=\"jform-lat\" type=\"text\" placeholder=\"auto-filled — or enter manually\"></div>\\n'\n"
    "        '      <div class=\"admin-field\"><label>Longitude</label><input id=\"jform-lng\" type=\"text\" placeholder=\"auto-filled — or enter manually\"></div>\\n'\n"
    "        '      <button class=\"btn-ghost\" type=\"button\" style=\"width:100%;margin-bottom:14px\" onclick=\"jformAutoGeocode(true)\">&#128269;&nbsp; Re-check Coordinates</button>\\n'\n"
)

# ── JS: adminOpenJourneysEditor / saveAdminJourney / new geocode fn ─────
OLD_JS = """function adminOpenJourneysEditor(){
  document.getElementById('admin-choice-screen').style.display='none';
  document.getElementById('admin-journeys-screen').style.display='block';
  document.getElementById('jform-name').value='';
  document.getElementById('jform-region').value='';
  document.getElementById('jform-lat').value='';
  document.getElementById('jform-lng').value='';
  document.getElementById('jform-gallery').value='';
  document.getElementById('jform-error').style.display='none';
  adminJourneysSetType('india');
}

function adminJourneysSetType(type){
  _jformType = type;
  document.getElementById('jform-type-india').classList.toggle('selected', type==='india');
  document.getElementById('jform-type-world').classList.toggle('selected', type==='world');
  document.getElementById('jform-region-label').textContent = type==='india' ? 'State' : 'Country';
}

function saveAdminJourney(){
  var name = document.getElementById('jform-name').value.trim();
  var region = document.getElementById('jform-region').value.trim();
  var lat = parseFloat(document.getElementById('jform-lat').value);
  var lng = parseFloat(document.getElementById('jform-lng').value);
  var gallery = document.getElementById('jform-gallery').value.trim();
  var errEl = document.getElementById('jform-error');

  if(!name || !region || isNaN(lat) || isNaN(lng)){
    errEl.textContent = 'Please fill in name, state/country, latitude and longitude.';
    errEl.style.display='block';
    return;
  }
  errEl.style.display='none';

  var payload = {
    type: _jformType,
    name: name,
    lat: lat,
    lng: lng,
    gallery: gallery
  };
  if(_jformType === 'india'){ payload.state = region; }
  else { payload.country = region; }"""

NEW_JS = """function adminOpenJourneysEditor(){
  document.getElementById('admin-choice-screen').style.display='none';
  document.getElementById('admin-journeys-screen').style.display='block';
  document.getElementById('jform-name').value='';
  document.getElementById('jform-region').value='';
  document.getElementById('jform-lat').value='';
  document.getElementById('jform-lng').value='';
  document.getElementById('jform-geocode-status').textContent='';
  document.getElementById('jform-error').style.display='none';
  adminJourneysSetType('india');
}

function adminJourneysSetType(type){
  _jformType = type;
  document.getElementById('jform-type-india').classList.toggle('selected', type==='india');
  document.getElementById('jform-type-world').classList.toggle('selected', type==='world');
  document.getElementById('jform-region-label').textContent = type==='india' ? 'State' : 'Country';
}

function jformAutoGeocode(force){
  var name = document.getElementById('jform-name').value.trim();
  var region = document.getElementById('jform-region').value.trim();
  var statusEl = document.getElementById('jform-geocode-status');
  var latEl = document.getElementById('jform-lat');
  var lngEl = document.getElementById('jform-lng');

  if(!name || !region) return;
  /* Don't clobber a manually-entered value unless the user explicitly asked to re-check */
  if(!force && (latEl.value.trim() || lngEl.value.trim())) return;

  var query = name + ', ' + region;
  statusEl.textContent = 'Looking up coordinates…';
  fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q=' + encodeURIComponent(query))
    .then(function(r){ return r.json(); })
    .then(function(results){
      if(results && results.length){
        latEl.value = parseFloat(results[0].lat).toFixed(4);
        lngEl.value = parseFloat(results[0].lon).toFixed(4);
        statusEl.textContent = '✓ Coordinates found — check the pin looks right, or edit manually.';
      } else {
        statusEl.textContent = 'No match found — enter coordinates manually.';
      }
    })
    .catch(function(){
      statusEl.textContent = 'Lookup failed — enter coordinates manually.';
    });
}

function saveAdminJourney(){
  var name = document.getElementById('jform-name').value.trim();
  var region = document.getElementById('jform-region').value.trim();
  var lat = parseFloat(document.getElementById('jform-lat').value);
  var lng = parseFloat(document.getElementById('jform-lng').value);
  var errEl = document.getElementById('jform-error');

  if(!name || !region || isNaN(lat) || isNaN(lng)){
    errEl.textContent = 'Please fill in name, state/country, and coordinates (auto-lookup runs when you leave the state/country field).';
    errEl.style.display='block';
    return;
  }
  errEl.style.display='none';

  var payload = {
    type: _jformType,
    name: name,
    lat: lat,
    lng: lng
  };
  if(_jformType === 'india'){ payload.state = region; }
  else { payload.country = region; }"""


def main():
    if not os.path.exists(SCRIPT_PATH):
        print(f"ERROR: could not find {SCRIPT_PATH}")
        return

    with open(SCRIPT_PATH, "r", encoding="utf-8") as f:
        source = f.read()

    if "jformAutoGeocode" in source:
        print("This file already looks patched (found jformAutoGeocode). Stopping — nothing changed.")
        return

    if "adminOpenJourneysEditor" not in source:
        print("ERROR: Part 3 (patch_journeys_admin_ui.py) doesn't look like it's been run yet.")
        print("Run that first, then re-run this script.")
        return

    if OLD_FIELDS not in source:
        print("ERROR: could not find the expected form-fields HTML block.")
        print("Stopping without changing anything — the file may differ from what this script expects.")
        return

    if OLD_JS not in source:
        print("ERROR: could not find the expected JS functions block.")
        print("Stopping without changing anything — the file may differ from what this script expects.")
        return

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = SCRIPT_PATH + f".bak_{ts}"
    shutil.copyfile(SCRIPT_PATH, backup_path)
    print(f"Backup written: {backup_path}")

    source = source.replace(OLD_FIELDS, NEW_FIELDS, 1)
    source = source.replace(OLD_JS, NEW_JS, 1)

    with open(SCRIPT_PATH, "w", encoding="utf-8") as f:
        f.write(source)

    print(f"\nDone. {SCRIPT_PATH} updated.")
    print("- Removed the manual Gallery Link field (that link forms automatically")
    print("  once you tag photos for the place via Edit Tags — no manual step needed).")
    print("- Added auto-geocoding: leaving the State/Country field now looks up")
    print("  lat/lng automatically. A 'Re-check Coordinates' button lets you redo it.")
    print(f"\nIf anything looks wrong, restore with:\n  cp {backup_path} {SCRIPT_PATH}")


if __name__ == "__main__":
    main()
